generator: "Luma"
model_version: "ray-flash-2"
prompt_enhancement: True
openai_key_dir: "/sotossta/DecepTIV/generate_fake_videos/keys/API_KEY_OPENAI"
luma_key_dir: "/sotossta/DecepTIV/generate_fake_videos/keys/API_KEY_LUMA"